// ─────────────────────────────────────────────
// TO ADD A NEW COLLECTION:
// 1. Create a folder:  images/collections/your-id/
// 2. Add photos + a cover image
// 3. Add an entry below — that's it.
// ─────────────────────────────────────────────

export const collections = [
  {
    id: "malcolm-todd",
    title: "Malcolm Todd",
    description: "Malcolm Todd @ CUP Springfest, February 2026.",
    cover: "images/collections/finished malcom todd/Malcolm Todd @CUP Springfest 2-28-26 by Isabel Yeow - 1.jpg",
    photos: Array.from({ length: 29 }, (_, i) =>
      `images/collections/finished malcom todd/Malcolm Todd @CUP Springfest 2-28-26 by Isabel Yeow - ${i + 1}.jpg`
    ),
  },
  {
    id: "cup-photoshoot",
    title: "CUP Photoshoot",
    description: "A photoshoot at CUP.",
    cover: "images/collections/cup photoshoot/DSC04424.jpg",
    photos: [
      "images/collections/cup photoshoot/DSC04424.jpg",
      "images/collections/cup photoshoot/DSC04426.jpg",
      "images/collections/cup photoshoot/DSC04431.jpg",
      "images/collections/cup photoshoot/DSC04434.jpg",
      "images/collections/cup photoshoot/DSC04444.jpg",
      "images/collections/cup photoshoot/DSC04445.jpg",
      "images/collections/cup photoshoot/DSC04455.jpg",
      "images/collections/cup photoshoot/DSC04515.jpg",
      "images/collections/cup photoshoot/DSC04528.jpg",
      "images/collections/cup photoshoot/DSC04537.jpg",
      "images/collections/cup photoshoot/DSC04543.jpg",
      "images/collections/cup photoshoot/DSC04546.jpg",
      "images/collections/cup photoshoot/DSC04547.jpg",
      "images/collections/cup photoshoot/DSC04548.jpg",
      "images/collections/cup photoshoot/DSC04550.jpg",
      "images/collections/cup photoshoot/DSC04560.jpg",
      "images/collections/cup photoshoot/DSC04561.jpg",
      "images/collections/cup photoshoot/DSC04564.jpg",
      "images/collections/cup photoshoot/DSC04565.jpg",
      "images/collections/cup photoshoot/DSC04566.jpg",
      "images/collections/cup photoshoot/DSC04567.jpg",
      "images/collections/cup photoshoot/DSC04569.jpg",
      "images/collections/cup photoshoot/DSC04571.jpg",
      "images/collections/cup photoshoot/DSC04572.jpg",
      "images/collections/cup photoshoot/DSC04577.jpg",
      "images/collections/cup photoshoot/DSC04579.jpg",
      "images/collections/cup photoshoot/DSC04581.jpg",
      "images/collections/cup photoshoot/DSC04585.jpg",
    ],
  },
  {
    id: "colored-prof",
    title: "Whats on your mind",
    description: "A collection of Art",
    cover: "images/collections/colored prof/Whats on your mind -  Isabel Yeow-1.jpg",
    photos: Array.from({ length: 17 }, (_, i) =>
      `images/collections/colored prof/Whats on your mind -  Isabel Yeow-${i + 1}.jpg`
    ),
  },
  {
    id: "cuppcake",
    title: "Cuppcake",
    description: "Cuppcake concert.",
    cover: "images/collections/cupcake final/DSC05312.jpg",
    photos: [
      "images/collections/cupcake final/DSC05312.jpg",
      "images/collections/cupcake final/DSC05315.jpg",
      "images/collections/cupcake final/DSC05321.jpg",
      "images/collections/cupcake final/DSC05322.jpg",
      "images/collections/cupcake final/DSC05323.jpg",
      "images/collections/cupcake final/DSC05324.jpg",
      "images/collections/cupcake final/DSC05325.jpg",
      "images/collections/cupcake final/DSC05328.jpg",
      "images/collections/cupcake final/DSC05330.jpg",
      "images/collections/cupcake final/DSC05332.jpg",
      "images/collections/cupcake final/DSC05333.jpg",
      "images/collections/cupcake final/DSC05336.jpg",
      "images/collections/cupcake final/DSC05339.jpg",
      "images/collections/cupcake final/DSC05340.jpg",
      "images/collections/cupcake final/DSC05353.jpg",
      "images/collections/cupcake final/DSC05354.jpg",
      "images/collections/cupcake final/DSC05355.jpg",
      "images/collections/cupcake final/DSC05357.jpg",
      "images/collections/cupcake final/DSC05358.jpg",
      "images/collections/cupcake final/DSC05359.jpg",
      "images/collections/cupcake final/DSC05360.jpg",
      "images/collections/cupcake final/DSC05361.jpg",
      "images/collections/cupcake final/DSC05373.jpg",
      "images/collections/cupcake final/DSC05374.jpg",
      "images/collections/cupcake final/DSC05388.jpg",
      "images/collections/cupcake final/DSC05389.jpg",
      "images/collections/cupcake final/DSC05398.jpg",
      "images/collections/cupcake final/DSC05399.jpg",
      "images/collections/cupcake final/DSC05404.jpg",
      "images/collections/cupcake final/DSC05405.jpg",
      "images/collections/cupcake final/DSC05406.jpg",
      "images/collections/cupcake final/DSC05407.jpg",
      "images/collections/cupcake final/DSC05414.jpg",
      "images/collections/cupcake final/DSC05415.jpg",
      "images/collections/cupcake final/DSC05418.jpg",
      "images/collections/cupcake final/DSC05427.jpg",
      "images/collections/cupcake final/DSC05432.jpg",
      "images/collections/cupcake final/DSC05434.jpg",
      "images/collections/cupcake final/DSC05436.jpg",
      "images/collections/cupcake final/DSC05445.jpg",
      "images/collections/cupcake final/DSC05447.jpg",
      "images/collections/cupcake final/DSC05453.jpg",
      "images/collections/cupcake final/DSC05454.jpg",
      "images/collections/cupcake final/DSC05462.jpg",
      "images/collections/cupcake final/DSC05464.jpg",
      "images/collections/cupcake final/DSC05465.jpg",
      "images/collections/cupcake final/DSC05466.jpg",
      "images/collections/cupcake final/DSC05476.jpg",
      "images/collections/cupcake final/DSC05481.jpg",
      "images/collections/cupcake final/DSC05482.jpg",
      "images/collections/cupcake final/DSC05485.jpg",
      "images/collections/cupcake final/DSC05489.jpg",
      "images/collections/cupcake final/DSC05501.jpg",
    ],
  },
  {
    id: "beno",
    title: "Beno",
    description: "Beno @ CUP Springfest, February 2026.",
    cover: "images/collections/finished beno/Beno @CUP Springfest 2-28-26 by Isabel Yeow - 1.jpg",
    photos: Array.from({ length: 28 }, (_, i) =>
      `images/collections/finished beno/Beno @CUP Springfest 2-28-26 by Isabel Yeow - ${i + 1}.jpg`
    ),
  },
  {
    id: "cherry-crisis",
    title: "Cherry Crisis",
    description: "Cherry Crisis @ CUP Springfest, February 2026.",
    cover: "images/collections/finished cherry crisis/Cherry Crisis @CUP Springfest 2-28-26 by Isabel Yeow - 1.jpg",
    photos: Array.from({ length: 26 }, (_, i) =>
      `images/collections/finished cherry crisis/Cherry Crisis @CUP Springfest 2-28-26 by Isabel Yeow - ${i + 1}.jpg`
    ),
  },
  {
    id: "japan-2026",
    title: "Japan 2026",
    description: "Japan 2026.",
    cover: "images/collections/japan 2026 /DSC00241.jpg",
    photos: [
      "images/collections/japan 2026 /DSC00241.jpg",
      "images/collections/japan 2026 /DSC00243.jpg",
      "images/collections/japan 2026 /DSC00244.jpg",
      "images/collections/japan 2026 /DSC00246.jpg",
      "images/collections/japan 2026 /DSC00251.jpg",
      "images/collections/japan 2026 /DSC00268-2.jpg",
      "images/collections/japan 2026 /DSC00271.jpg",
      "images/collections/japan 2026 /DSC00317.jpg",
      "images/collections/japan 2026 /DSC00338.jpg",
      "images/collections/japan 2026 /DSC00341.jpg",
      "images/collections/japan 2026 /DSC00342.jpg",
      "images/collections/japan 2026 /DSC00413.jpg",
      "images/collections/japan 2026 /DSC00417.jpg",
      "images/collections/japan 2026 /DSC00488.jpg",
      "images/collections/japan 2026 /DSC00491.jpg",
      "images/collections/japan 2026 /DSC00492.jpg",
      "images/collections/japan 2026 /DSC00495.jpg",
      "images/collections/japan 2026 /DSC00499.jpg",
      "images/collections/japan 2026 /DSC00502.jpg",
      "images/collections/japan 2026 /DSC00593.jpg",
      "images/collections/japan 2026 /DSC00600.jpg",
      "images/collections/japan 2026 /DSC00623.jpg",
      "images/collections/japan 2026 /DSC00637.jpg",
      "images/collections/japan 2026 /DSC00638.jpg",
      "images/collections/japan 2026 /DSC01037.jpg",
      "images/collections/japan 2026 /DSC01038.jpg",
      "images/collections/japan 2026 /DSC01047.jpg",
      "images/collections/japan 2026 /DSC01098.jpg",
      "images/collections/japan 2026 /DSC01140.jpg",
      "images/collections/japan 2026 /DSC01141.jpg",
      "images/collections/japan 2026 /DSC01195.jpg",
      "images/collections/japan 2026 /DSC01215.jpg",
      "images/collections/japan 2026 /DSC01286.jpg",
    ],
  },
  {
    id: "hiya-riya",
    title: "Hiya Riya",
    description: "Hiya Riya @ MSSA.",
    cover: "images/collections/hiya-riya/Hiya Riya MSSA -  Isabel Yeow-1.jpg",
    photos: Array.from({ length: 39 }, (_, i) =>
      `images/collections/hiya-riya/Hiya Riya MSSA -  Isabel Yeow-${i + 1}.jpg`
    ),
  },
  {
    id: "sing-and-serve",
    title: "Sing & Serve",
    description: "Sing & Serve @ RSA.",
    cover: "images/collections/Sing & Serve/Sing & Serve RSA - Isabel Yeow-1.jpg",
    photos: Array.from({ length: 21 }, (_, i) =>
      `images/collections/Sing & Serve/Sing & Serve RSA - Isabel Yeow-${i + 1}.jpg`
    ),
  },
];
